version: '3'

services:
  app:
    build: ./
    working_dir: /usr/src/app
    environment:
      TZ: Asia/Tokyo
      LANG: ja_JP.UTF-8
      PHPRC: /etc/php
    volumes:
      - ./src:/usr/src/app
      - ./php.ini:/etc/php/7.4/cli/php.ini
  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - "1080:1080"
